---
title: "Data Overview"
output: pdf_document
---

```{r}
library(tseries)
library(forecast)
library(TSA)
```

```{r}
data <- read.csv('data/avg_sst_california.csv')

ts_data <- ts(data$sst, start = c(1981, 9), frequency = 12)
ts_train <- window(ts_data, start=c(1981, 9), end=c(2023, 12))
ts_test <- window(ts_data, start=c(2024, 1), end=c(2024, 12))
```

```{r}
tsdisplay(ts_data)
tsdisplay(ts_train)
tsdisplay(ts_test)
```
```{r}
stlf(ts_data)
```
```{r}
spectrum <- periodogram(ts_data)

# Get indices of the top 5 peaks
top_indices <- order(spectrum$spec, decreasing = TRUE)[1:5]

# Compute the periods
top_periods <- 1 / spectrum$freq[top_indices]

# Print the top 5 periods
print("Top 5 periods with highest magnitude:")
print(top_periods)
```

```{r}
library(forecast)
library(MuMIn)

forecast_naive <- snaive(ts_train, h=12)

# Calculate MAPE
mape <- mean(abs((ts_test - forecast_naive$mean) / ts_test)) * 100

# Calculate RMSE
rmse <- sqrt(mean((ts_test - forecast_naive$mean)^2))

# Print results
cat("MAPE:", mape, "\n")
cat("RMSE:", rmse, "\n")


# Plot actual test data
plot(ts_test, type = "l", col = "black", lwd = 2, ylim = range(c(ts_test, forecast_naive$mean)),
     ylab = "Temperature", xlab = "Time", main = "Forecast vs. Actual Test Data")

# Add forecasted values
lines(forecast_naive$mean, col = "red", lwd = 2, lty = 2)

# Add legend
legend("topleft", legend = c("Actual", "Forecast"), col = c("black", "red"),
       lty = c(1, 2), lwd = 2)
```

```{r}
saveRDS(ts_train, "data/ts_train.rds")
saveRDS(ts_test, "data/ts_test.rds")
```